# Generated by Django 2.2 on 2019-04-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('genre', models.CharField(choices=[('RK', 'Rock'), ('JZ', 'Jazz'), ('MT', 'Metal')], default='Rock', max_length=5)),
                ('price', models.FloatField()),
                ('semi_acoustic', models.BooleanField(default=False)),
                ('capt_num', models.IntegerField(default=1)),
            ],
        ),
    ]
